version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./migrations:/app/migrations
    command: >
      /bin/sh -c "migrate -path /app/migrations -database sqlite3://test.db up && ./main"